### ISSUE TITLE
Adding shadow to player model?

### ISSUE THREAD

**Issue by astralscott** [matthias-schuetz/THREE-BasicThirdPersonGame#3]
Hey! Amazing stuff here. Thanks for putting it together.

I am trying to get my imported player model to cast a shadow, but I am not sure where to put the .castshadow = true.

Can you explain a lil more how I actually snag the model reference (from your demos)?

Thank you

**Comment by waldenn** [comment]
Hi,

You can set that option on the [light object](http://threejs.org/docs/#Reference/Lights/SpotLight), eg. "spotLight.castShadow = true;".

The model is in ThreeJS JSON format, like the [example used here](https://github.com/matthias-schuetz/THREE-BasicThirdPersonGame/blob/master/js/game/game.models.js). You can just copy and paste that "player" object data and then [load](http://threejs.org/docs/#Reference/Loaders/JSONLoader) and use it. Please check the TreeJS docs, as they now have working examples of these API functions.

Hope that helps.

**Comment by matthias-schuetz** [comment]
Thanks waldenn for your answer.
In addition, I've created a fifth demo which implements THREE.js shadows and also makes the player cast a shadow. You need to add the "castShadow" property to _game.player.mesh but you also need to enable shadows in THREE.js first. Finally, you'll need a directional or spot light that casts the shadow. You need at least one of these light types in your scene. The API of THREE.js has changed and the properties for "shadowMap" are different. Below are the commands for the version that is used by THREE.BasicThirdPersonGame.

```javascript
// Enable shadows
_game.player.mesh.castShadow = true;
_game.player.mesh.receiveShadow = true;

// Enable shadows
_three.renderer.shadowMapEnabled = true;
_three.renderer.shadowMapType = THREE.PCFSoftShadowMap;
```

The fifth demo is now also included in this repository and you can find a running demo online here:

[THREE.BasicThirdPersonGame: Demo 5 - Shadows](http://matthiasschuetz.com/three-basicthirdpersongame/demos/demo5_shadows.html)

I hope this answers your question.
